BookLoansPorject/Controllers/BooksController.cs
using BookLoansPorject.Models;
using BookLoansPorject.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using X.PagedList;

namespace BookLoansPorject.Controllers
{
    [Authorize]
    public class BooksController : Controller
    {
        private readonly BookDbContext db = new BookDbContext();
        // GET: Books
        [AllowAnonymous]
        public async Task<ActionResult> Index(int pg = 1)
        {
            var data = await db.Books.OrderBy(a => a.BookId).ToPagedListAsync(pg, 5);
            return View(data);
        }
        public ActionResult Create()
        {

            BookViewModel b = new BookViewModel();
            b.BookLoans.Add(new BookLoan { });
            return View(b);
        }
        [HttpPost]
        public ActionResult Create(BookViewModel data, string act = "")
        {
            if (act == "add")
            {
                data.BookLoans.Add(new BookLoan { });

                foreach (var item in ModelState.Values)
                {
                    item.Errors.Clear();
                }
            }
            if (act.StartsWith("remove"))
            {
                int index = int.Parse(act.Substring(act.IndexOf("_") + 1));
                data.BookLoans.RemoveAt(index);
                foreach (var item in ModelState.Values)
                {
                    item.Errors.Clear();
                }
            }
            if (act == "insert")
            {
                if (ModelState.IsValid)
                {
                    var b = new Book
                    {
                        Title = data.Title,
                        Author = data.Author,
                        Genre = data.Genre,
                        IsAvailable = data.IsAvailable,
                    };
                    string ext = Path.GetExtension(data.BookCover.FileName);
                    string fileName = Path.GetFileNameWithoutExtension(Path.GetRandomFileName()) + ext;
                    string savePath = Server.MapPath("~/Pictures/") + fileName;
                    data.BookCover.SaveAs(savePath);
                    b.BookCover = fileName;
                    foreach (var l in data.BookLoans)
                    {

                        b.BookLoans.Add(l);
                    }
                    db.Books.Add(b);
                    db.SaveChanges();
                }
            }
            ViewBag.Act = act;
            return PartialView("_CreatePartial", data);
        }
        public ActionResult Edit(int id)
        {
            var a = db.Books
              .Select(x => new BookEditModel
              {
                  BookId = x.BookId,
                  Title = x.Title,
                  Author = x.Author,
                  Genre = x.Genre,
                  IsAvailable = x.IsAvailable,
                  BookLoans = x.BookLoans.ToList()
              })
              .FirstOrDefault(x => x.BookId == id);

            ViewBag.CurrentPic = db.Books.First(x => x.BookId == id).BookCover;

            return View(a);
        }

        [HttpPost]
        public ActionResult Edit(BookEditModel data, string act = "")
        {


            if (act == "add")
            {

                data.BookLoans.Add(new BookLoan { });
            }

            if (act.StartsWith("remove"))
            {

                int index = int.Parse(act.Substring(act.IndexOf("_") + 1));

                data.BookLoans.RemoveAt(index);
            }

            if (act == "update")
            {

                if (ModelState.IsValid)
                {

                    var a = db.Books.First(x => x.BookId == data.BookId);

                    a.Title = data.Title;
                    a.Author = data.Author;
                    a.Genre = data.Genre;
                    a.IsAvailable = data.IsAvailable;
                    if (data.BookCover != null)
                    {

                        string ext = Path.GetExtension(data.BookCover.FileName);
                        string fileName = Path.GetFileNameWithoutExtension(Path.GetRandomFileName()) + ext;
                        string savePath = Server.MapPath("~/Pictures/") + fileName;
                        data.BookCover.SaveAs(savePath);
                        a.BookCover = fileName;
                    }

                    db.Books.RemoveRange(db.Books.Where(x => x.BookId == data.BookId).ToList());

                    foreach (var item in data.BookLoans)
                    {
                        a.BookLoans.Add(new BookLoan
                        {
                            BorrowerName = item.BorrowerName,
                            Address = item.Address,
                            Phone = item.Phone,
                            LoanDate = item.LoanDate,
                            ReturnDate = item.ReturnDate,
                        });
                    }
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            return View(data);
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var book = new Book { BookId = id };
            db.Entry(book).State = System.Data.Entity.EntityState.Deleted;
            db.SaveChanges();
            return Json(new { success = true, deleted = id });
        }
    }
}

BookLoansPorject/Views/Shared/_Fail.cshtml
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>Failed!</strong> Failed to save into database.
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

BookLoansPorject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - BookLoanInfo</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.bundle.js"></script>
    <style>
        body {
            padding-top: 70px;         
        }

        .main {
            min-height: calc(100vh - 110px);
        }
    </style>
    @RenderSection("styles", false)
</head>
<body>
    <nav class="navbar navbar-expand-md bg-info-subtle fixed-top shadow-sm px-2">
        <div class="container-fluid">
            <span class="navbar-brand">Open Library<sub><sub><i class="bi bi-book"></i></sub></sub> <sup>Borrowing Books from our Library</sup></span>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nv" aria-controls="nv" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse" id="nv">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Home")"><i class="bi bi-house-heart"></i> Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Books")"><i class="bi bi-book-fill"></i> Books</a>
                    </li>
                    @if (Request.IsAuthenticated)
                    {
                        <li class="nav-item">
                            @Html.ActionLink("Logout", "Logout", "Accounts", new { }, new { @class = "nav-link" })
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            @Html.ActionLink("Register", "Register", "Accounts", new { }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Login", "Login", "Accounts", new { }, new { @class = "nav-link" })
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>

    <main class="container-fluid main ">
        @RenderBody()
    </main>
    <footer class="container-fluid">
        <p>&copy; @DateTime.Now.Year - Open Library Management</p>
    </footer>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    @RenderSection("scripts", false)
</body>
</html>

BookLoansPorject/Views/Shared/_Success.cshtml
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>Success!</strong> Data saved into database.
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

BookLoansPorject/Views/Shared/_Update.cshtml
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>Success!</strong> Data updated into database.
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>